version: '3'
services:
  strongbox-web-integration-tests-sbt:
    image: strongboxci/alpine:jdk8-mvn3.6-sbt1.3
    volumes:
      - $HOME/.m2/repository:/home/jenkins/.m2/repository
      - ../:/workspace
    working_dir: /workspace/sbt
    command: mvn clean install -U
